<!DOCTYPE shipClassList [
		<!ELEMENT shipClassList (list)*>
		<!ELEMENT list (shipClass)*>
		<!ELEMENT shipClass (price|ship)*>
		<!ATTLIST shipClass
				className CDATA #REQUIRED>
		<!ELEMENT price (#PCDATA)>
		<!ELEMENT ship (dwt|grossTonnage|netTonnage|maxSpeed|loa|beam|draft|maxFuel|dailyCost|maxTEU|engines|lngCapacity)*>
		<!ATTLIST ship
				class CDATA #REQUIRED>
		<!ELEMENT dwt (#PCDATA)>
		<!ELEMENT grossTonnage (#PCDATA)>
		<!ELEMENT netTonnage (#PCDATA)>
		<!ELEMENT maxSpeed (#PCDATA)>
		<!ELEMENT loa (#PCDATA)>
		<!ELEMENT beam (#PCDATA)>
		<!ELEMENT draft (#PCDATA)>
		<!ELEMENT maxFuel (#PCDATA)>
		<!ELEMENT dailyCost (#PCDATA)>
		<!ELEMENT maxTEU (#PCDATA)>
		<!ELEMENT engines (engine)*>
		<!ELEMENT engine (#PCDATA)>
		<!ELEMENT lngCapacity (#PCDATA)>
		]>
<shipClassList>
	<!--
	   <shipclass>
		   <className>Feeder</className>
		   <price></price>
		   <ship>
			   <buildYear>2007</buildYear>
			   <className>CCS</className>
			   <dwt>4200T</dwt>
			   <grossTonnage>2970</grossTonnage>
			   <netTonnage>1579</netTonnage>
			   <loa>94.80M</loa>
			   <lbp>87.30</lbp>
			   <breadth>15.20</breadth>
			   <depth>7.80</depth>
			   <draft>6.00</draft>
			   <engineType>8320ZCd-6 GUANGZHOU DIESEL</engineType>
			   <maxSpeed>13</maxSpeed>
			   FUEL CONSUMPTION : 7.5MT IFO 120CST, 0.6MT MGO PER DAY
		   </ship>
	   </shipclass>
	   -->
	<list>
		<shipClass className="Delmas Libreville">
			<price>15000000</price>
			<ship class="kop.ships.blueprint.ContainerShipBlueprint">
				<dwt>27100</dwt>
				<grossTonnage>24053</grossTonnage>
				<netTonnage>12958</netTonnage>
				<maxSpeed>21.0</maxSpeed>
				<loa>205.5</loa>
				<beam>27.4</beam>
				<draft>10.12</draft>
				<maxFuel>5000</maxFuel>
				<dailyCost>1200</dailyCost>
				<maxTEU>2109</maxTEU>
				<engines>
					<engine>B&amp;W 7L60MC</engine>
				</engines>
			</ship>
		</shipClass>
		<shipClass className="Heinz Schepers">
			<price>10000000</price>
			<ship class="kop.ships.blueprint.ContainerShipBlueprint">
				<dwt>5335</dwt>
				<grossTonnage>3992</grossTonnage>
				<netTonnage>2233</netTonnage>
				<maxSpeed>15.0</maxSpeed>
				<loa>101.11</loa>
				<beam>18.2</beam>
				<draft>4.4</draft>
				<maxFuel>0.0</maxFuel>
				<dailyCost>0.0</dailyCost>
				<maxTEU>509</maxTEU>
				<engines>
					<engine>TBD 645 L9</engine>
				</engines>
			</ship>
		</shipClass>
		<shipClass className="TI class tanker">
			<price>120000000</price>
			<ship class="kop.ships.blueprint.TankerShipBlueprint">
				<dwt>441585</dwt>
				<loa>380.0</loa>
				<beam>68.0</beam>
				<draft>24.5</draft>
				<grossTonnage>234006</grossTonnage>
				<netTonnage>162447</netTonnage>
				<maxSpeed>16.5</maxSpeed>
				<maxFuel>11996</maxFuel>
				<dailyCost>10000</dailyCost>
				<engines>
					<engine>9RTA84T-D</engine>
				</engines>
			</ship>
		</shipClass>
		<shipClass className="P-class tanker">
			<price>100000000</price>
			<ship class="kop.ships.blueprint.TankerShipBlueprint">
				<dwt>306397</dwt>
				<engines>
					<engine>B&amp;W 7S80MC</engine>
				</engines>
				<loa>333.96</loa>
				<draft>22.52</draft>
				<beam>58</beam>
				<maxSpeed>15.0</maxSpeed>
				<maxFuel>7547</maxFuel>
				<grossTonnage>160216</grossTonnage>
				<netTonnage>105889</netTonnage>
				<dailyCost>8000</dailyCost>
			</ship>
		</shipClass>
		<shipClass className="Gem class">
			<price>100000000</price>
			<ship class="kop.ships.blueprint.LNGCarrierBlueprint">
				<beam>44.2</beam>
				<dailyCost>0.0</dailyCost>
				<draft>11.47</draft>
				<dwt>76000</dwt>
				<engines>
					<engine>12V50DF</engine>
					<engine>12V50DF</engine>
					<engine>6V50DF</engine>
					<engine>6V50DF</engine>
				</engines>
				<grossTonnage>99600</grossTonnage>
				<lngCapacity>155000</lngCapacity>
				<netTonnage>31576</netTonnage>
				<maxSpeed>20.0</maxSpeed>
				<loa>288.0</loa>
				<maxFuel>6700</maxFuel>
			</ship>
		</shipClass>
		<!--
		<shipClass className="E-class container ship">
			<price>145000000</price>
			<ship class="kop.ships.blueprint.ContainerShipBlueprint">
				<dwt>156907</dwt>
				<engine>14RT-Flex96C</engine>
				<maxSpeed>25.5</maxSpeed>
			</ship>
		</shipClass>
		-->
	</list>
</shipClassList>